// strings.js — the game's UI texts in English and German (#9). Pure: no DOM, no window, so node --test can import it.
// A value is either a string or a function of the call's arguments. Proper names (checkpoints, landmarks, streets,
// Gemeinden) are passed in as arguments and never translated.
// Strings may carry <b>/<br>/<span> markup: they are our own constants and are written with innerHTML.

const small = (s) => `<span style="font-size:17px">${s}</span>`;

const en = {
  // ---- start / result screen ----
  sub: 'Codename Rhyflitzer · Prototype v0.2',
  intro: 'Sisseln → Sisslerfeld → Stein → Bad Säckingen. Five checkpoints in any order, then the finish at the Münsterplatz. The Holzbrücke is for pedestrians. Nobody told the timer.',
  finishedText: 'Münsterplatz reached. Retry for a better line, or take the other bridge next time.',
  start: 'Start',
  retry: 'Retry',
  styleLabel: 'Style:',
  styleOriginal: 'Original',
  styleSmooth: 'Smooth',
  loadTerrain: 'Load terrain (.mmh)',
  useMadeUp: 'Use made-up terrain',
  terrainMadeUp: 'Terrain: made up (smooth hills, not measured)',
  terrainMeasured: (own, w, h, step, sources) => `Terrain: measured${own ? ' (your file)' : ''} · ${w}×${h} at ${step} m · ${sources}`,
  terrainSaving: 'Saving terrain, rebuilding the world…',
  terrainCouldNotLoad: (message) => `Could not load: ${message}`,
  errNotMmh: 'Not a Map Madness heightmap (MMH1)',
  errNoStorage: 'This browser blocks storage, so the terrain cannot be kept',
  blurbHand: 'Layout traced from OpenStreetMap by hand. Timer starts when you move.',
  blurbOsm: 'Roads, the Rhine, houses and landmarks from OpenStreetMap, terrain from swisstopo. Timer starts when you move.',
  worldOsm: (roads, buildings, sources) => `World: OpenStreetMap · ${roads} roads · ${buildings} buildings · ${sources}`,
  worldHand: 'World: traced by hand (no data/world_hochrhein.json)',
  newRecord: 'New record!',
  finished: 'Finished',
  notCountedJump: 'with a jump, not counted · ',
  notCountedFast: 'with time-lapse, not counted · ',
  notCountedHeli: 'with the helicopter, not counted · ',
  viaHolz: 'via the Holzbrücke · ',
  bestLower: 'best',
  keyHornMute: 'horn (also Enter) · mute',
  keyNitroJump: 'nitro (hold) · jump to a landmark',
  keyAllKeys: 'all keys',
  // ---- HUD ----
  mode: 'Time trial · Hochrhein',
  checkpointsLabel: 'checkpoints',
  ready: 'Ready',
  cpTarget: (number, name) => `Checkpoint ${number} · ${name}`,
  finishTarget: (name) => `Finish · ${name}`,
  time: 'Time',
  best: (time) => `Best ${time ?? '—'}`,
  damage: 'Damage',
  gear: 'Gear',
  trip: 'Trip',
  odo: (km) => `Total ${km} km · K resets trip`,
  map: 'Map · Hochrhein ·',
  compassAria: 'Compass',
  compassEast: 'E',
  speedoAria: 'Speedometer',
  steerLeft: 'Steer left',
  steerRight: 'Steer right',
  accelerate: 'Accelerate',
  brake: 'Brake',
  handbrake: 'Handbrake',
  // ---- toasts ----
  muted: 'Muted',
  soundOn: 'Sound on',
  camera: (view) => `Camera: ${view}`,
  camChase: 'Chase',
  camNear: 'Chase near',
  camCockpit: 'Cockpit',
  camBumper: 'Bumper',
  cpToast: (number, name) => `Checkpoint ${number}/5<br>${small(name)}`,
  holzToast: `Holzbrücke!<br>${small('Pedestrians only. Allegedly.')}`,
  fishes: 'Sleep with the fishes!',
  heliOn: 'Helicopter!',
  heliLanded: 'Landed',
  randomSpot: 'Random spot',
  fromMap: 'From the map',
  debugOn: 'Debug on',
  debugOff: 'Debug off',
  copied: 'Copied',
  copyFailed: 'Copy failed',
  boundsOn: 'Gemeinde boundaries on',
  boundsOff: 'Gemeinde boundaries off',
  boundsNoData: 'Gemeinde boundaries: no data',
  // ---- F1 help ----
  helpTitle: 'Keys · F1 closes',
  keyAccel: 'accelerate (W or ↑ also work)',
  keySteer: 'or ← →: steer · <b>S</b> / ↓ brake, reverse',
  keyHandbrake: 'handbrake (drift)',
  keyNitro: 'Nitro (hold)',
  keyTab: 'game speed ×3 (hold; the run is not recorded)',
  keySignals: 'Turn signals left · right',
  keyHorn: 'horn',
  keyCamera: 'camera: chase · near · cockpit · bumper',
  keyLookBack: 'look back (hold)',
  keyCar: 'show / hide the car',
  keyBounds: 'show / hide the Gemeinde boundaries',
  keyJump: 'jump to a landmark',
  keyHeli: 'helicopter: take off · land (Space climbs, Shift sinks)',
  keyZoom: 'zoom the map 1× · 2× · 4× · 8× (or the mouse wheel over it) · double-click or double-tap the map: put the car on the road there',
  keyTrip: 'reset the trip odometer',
  keyReset: 'back on the road',
  keyStyle: 'toggle graphic style',
  keyMute: 'mute',
  keyDebug: 'debug: coordinates, building heights (click the panel to copy · ?debug in the URL)',
  keyHelp: 'this help',
  // ---- J dialog ----
  jumpTitle: 'Jump to',
  jumpSearch: 'Search landmarks',
  jumpHint: 'type to search · ↑↓ Enter · J / Esc closes',
  chipAll: 'All',
};

const de = {
  sub: 'Codename Rhyflitzer · Prototyp v0.2',
  intro: 'Sisseln → Sisslerfeld → Stein → Bad Säckingen. Fünf Checkpoints in beliebiger Reihenfolge, dann das Ziel auf dem Münsterplatz. Die Holzbrücke ist für Fussgänger. Das hat der Stoppuhr niemand gesagt.',
  finishedText: 'Münsterplatz erreicht. Nochmals für eine bessere Linie – oder nächstes Mal die andere Brücke.',
  start: 'Start',
  retry: 'Nochmals',
  styleLabel: 'Stil:',
  styleOriginal: 'Original',
  styleSmooth: 'Glatt',
  loadTerrain: 'Gelände laden (.mmh)',
  useMadeUp: 'Erfundenes Gelände verwenden',
  terrainMadeUp: 'Gelände: erfunden (sanfte Hügel, nicht gemessen)',
  terrainMeasured: (own, w, h, step, sources) => `Gelände: gemessen${own ? ' (Deine Datei)' : ''} · ${w}×${h} zu ${step} m · ${sources}`,
  terrainSaving: 'Gelände wird gespeichert, die Welt neu aufgebaut…',
  terrainCouldNotLoad: (message) => `Konnte nicht geladen werden: ${message}`,
  errNotMmh: 'Keine Map-Madness-Höhenkarte (MMH1)',
  errNoStorage: 'Dieser Browser blockiert den Speicher, das Gelände kann nicht behalten werden',
  blurbHand: 'Strassennetz von Hand aus OpenStreetMap abgezeichnet. Die Zeit läuft, sobald Du fährst.',
  blurbOsm: 'Strassen, Rhein, Häuser und Wahrzeichen aus OpenStreetMap, Gelände von swisstopo. Die Zeit läuft, sobald Du fährst.',
  worldOsm: (roads, buildings, sources) => `Welt: OpenStreetMap · ${roads} Strassen · ${buildings} Gebäude · ${sources}`,
  worldHand: 'Welt: von Hand abgezeichnet (keine data/world_hochrhein.json)',
  newRecord: 'Neuer Rekord!',
  finished: 'Im Ziel',
  notCountedJump: 'mit Sprung, zählt nicht · ',
  notCountedFast: 'mit Zeitraffer, zählt nicht · ',
  notCountedHeli: 'mit Helikopter, zählt nicht · ',
  viaHolz: 'über die Holzbrücke · ',
  bestLower: 'Bestzeit',
  keyHornMute: 'Hupe (auch Enter) · Ton aus',
  keyNitroJump: 'Nitro (halten) · zu einem Wahrzeichen springen',
  keyAllKeys: 'alle Tasten',
  mode: 'Zeitfahren · Hochrhein',
  checkpointsLabel: 'Checkpoints',
  ready: 'Bereit',
  cpTarget: (number, name) => `Checkpoint ${number} · ${name}`,
  finishTarget: (name) => `Ziel · ${name}`,
  time: 'Zeit',
  best: (time) => `Bestzeit ${time ?? '—'}`,
  damage: 'Schaden',
  gear: 'Gang',
  trip: 'Trip',
  odo: (km) => `Total ${km} km · K setzt Trip zurück`,
  map: 'Karte · Hochrhein ·',
  compassAria: 'Kompass',
  compassEast: 'O',
  speedoAria: 'Tachometer',
  steerLeft: 'Links lenken',
  steerRight: 'Rechts lenken',
  accelerate: 'Gas geben',
  brake: 'Bremsen',
  handbrake: 'Handbremse',
  muted: 'Ton aus',
  soundOn: 'Ton an',
  camera: (view) => `Kamera: ${view}`,
  camChase: 'Verfolger',
  camNear: 'Verfolger nah',
  camCockpit: 'Cockpit',
  camBumper: 'Stossstange',
  cpToast: (number, name) => `Checkpoint ${number}/5<br>${small(name)}`,
  holzToast: `Holzbrücke!<br>${small('Nur für Fussgänger. Angeblich.')}`,
  fishes: 'Grüss mir die Fische!',
  heliOn: 'Helikopter!',
  heliLanded: 'Gelandet',
  randomSpot: 'Zufälliger Ort',
  fromMap: 'Von der Karte',
  debugOn: 'Debug an',
  debugOff: 'Debug aus',
  copied: 'Kopiert',
  copyFailed: 'Kopieren fehlgeschlagen',
  boundsOn: 'Gemeindegrenzen an',
  boundsOff: 'Gemeindegrenzen aus',
  boundsNoData: 'Gemeindegrenzen: keine Daten',
  helpTitle: 'Tasten · F1 schliesst',
  keyAccel: 'Gas geben (W oder ↑ gehen auch)',
  keySteer: 'oder ← →: lenken · <b>S</b> / ↓ bremsen, rückwärts',
  keyHandbrake: 'Handbremse (Drift)',
  keyNitro: 'Nitro (halten)',
  keyTab: 'Spieltempo ×3 (halten; die Fahrt zählt nicht)',
  keySignals: 'Blinker links · rechts',
  keyHorn: 'Hupe',
  keyCamera: 'Kamera: Verfolger · nah · Cockpit · Stossstange',
  keyLookBack: 'zurückschauen (halten)',
  keyCar: 'Auto zeigen / verstecken',
  keyBounds: 'Gemeindegrenzen ein- / ausblenden',
  keyJump: 'zu einem Wahrzeichen springen',
  keyHeli: 'Helikopter: abheben · landen (Leertaste steigt, Shift sinkt)',
  keyZoom: 'Karte zoomen 1× · 2× · 4× · 8× (oder Mausrad darüber) · Doppelklick oder Doppeltipp auf die Karte: Auto dort auf die Strasse setzen',
  keyTrip: 'Tageskilometer zurücksetzen',
  keyReset: 'zurück auf die Strasse',
  keyStyle: 'Grafikstil wechseln',
  keyMute: 'Ton aus',
  keyDebug: 'Debug: Koordinaten, Gebäudehöhen (Panel anklicken zum Kopieren · ?debug in der URL)',
  keyHelp: 'diese Hilfe',
  jumpTitle: 'Springen nach',
  jumpSearch: 'Wahrzeichen suchen',
  jumpHint: 'tippen zum Suchen · ↑↓ Enter · J / Esc schliesst',
  chipAll: 'Alle',
};

export const STRINGS = { en, de };

export function translate(lang, key, ...args) {
  const table = STRINGS[lang] || en;
  const value = key in table ? table[key] : key in en ? en[key] : key;
  return typeof value === 'function' ? value(...args) : value;
}
