// strings.js — the game's UI texts in English and German (#9). Pure: no DOM, no window, so node --test can import it.
// A value is either a string or a function of the call's arguments. Proper names (checkpoints, landmarks, streets,
// Gemeinden) are passed in as arguments and never translated.
// Strings may carry <b>/<br>/<span> markup: they are our own constants and are written with innerHTML.

const small = (s) => `<span style="font-size:17px">${s}</span>`;

const en = {
  // ---- start / result screen ----
  sub: 'Codename Rhyflitzer · Prototype v0.2',
  region: 'Region',
  regionMissing: (n) => `No data for ${n} yet — showing Hochrhein`,
  introEhrendingen: 'Oberdorf → Höhtal → Lägernbreite → St. Anna → Tiefenwaag. Five checkpoints in any order, then the finish Im Böndlern. The Wanderweg is for hikers. Nobody told the timer.',
  finishedEhrendingen: 'Im Böndlern reached. Retry for a better line, or take the Wanderweg next time.',
  blurbOsmEhrendingen: 'Roads, the Wanderweg, houses and the Surb from OpenStreetMap, terrain from swisstopo. Timer starts when you move.',
  intro: 'Sisseln → Sisslerfeld → Stein → Bad Säckingen. Five checkpoints in any order, then the finish at the Münsterplatz. The Holzbrücke is for pedestrians. Nobody told the timer.',
  finishedText: 'Münsterplatz reached. Retry for a better line, or take the other bridge next time.',
  start: 'Start',
  retry: 'Retry',
  styleLabel: 'Style:',
  styleOriginal: 'Original',
  styleSmooth: 'Smooth',
  loadTerrain: 'Load terrain (.mmh)',
  useMadeUp: 'Use made-up terrain',
  terrainMadeUp: 'Terrain: made up (smooth hills, not measured)',
  terrainMeasured: (own, w, h, step, sources) => `Terrain: measured${own ? ' (your file)' : ''} · ${w}×${h} at ${step} m · ${sources}`,
  terrainSaving: 'Saving terrain, rebuilding the world…',
  terrainCouldNotLoad: (message) => `Could not load: ${message}`,
  errNotMmh: 'Not a Map Madness heightmap (MMH1)',
  errNoStorage: 'This browser blocks storage, so the terrain cannot be kept',
  blurbHand: 'Layout traced from OpenStreetMap by hand. Timer starts when you move.',
  blurbOsm: 'Roads, the Rhine, houses and landmarks from OpenStreetMap, terrain from swisstopo. Timer starts when you move.',
  worldOsm: (roads, buildings, sources) => `World: OpenStreetMap · ${roads} roads · ${buildings} buildings · ${sources}`,
  worldHand: 'World: traced by hand (no data/world_hochrhein.json)',
  newRecord: 'New record!',
  finished: 'Finished',
  notCountedJump: 'with a jump, not counted · ',
  notCountedHeli: 'with the helicopter, not counted · ',
  notCountedAuto: 'with the autopilot, not counted · ',
  viaHolz: 'via the Holzbrücke · ',
  bestLower: 'best',
  keyHornMute: 'horn (also Enter) · mute',
  keyNitroJump: 'nitro (hold) · jump to a landmark',
  keyAllKeys: 'all keys',
  // ---- HUD ----
  mode: (r) => `Time trial · ${r}`,
  checkpointsLabel: 'checkpoints',
  ready: 'Ready',
  cpTarget: (number, name) => `Checkpoint ${number} · ${name}`,
  finishTarget: (name) => `Finish · ${name}`,
  time: 'Time',
  best: (time) => `Best ${time ?? '—'}`,
  damage: 'Damage',
  gear: 'Gear',
  trip: 'Trip',
  odo: (km) => `Total ${km} km · K resets trip`,
  map: (r) => `Map · ${r} ·`,
  compassAria: 'Compass',
  compassEast: 'E',
  speedoAria: 'Speedometer',
  steerLeft: 'Steer left',
  steerRight: 'Steer right',
  accelerate: 'Accelerate',
  brake: 'Brake',
  handbrake: 'Handbrake',
  // ---- toasts ----
  muted: 'Muted',
  soundOn: 'Sound on',
  photoSaved: 'Photo taken',
  photoFailed: 'Photo failed',
  camera: (view) => `Camera: ${view}`,
  camChase: 'Chase',
  camNear: 'Chase near',
  camCockpit: 'Cockpit',
  camBumper: 'Bumper',
  cpToast: (number, name) => `Checkpoint ${number}/5<br>${small(name)}`,
  // ---- surprise hunt (#108) ----
  hunt: 'Surprise hunt',
  modeHunt: 'Surprise hunt · Hochrhein',
  presentsLabel: 'presents',
  presentTarget: 'Nearest present',
  huntStart: 'Find the 5 presents! Follow the arrow.',
  presentToast: (number, total, line) => `Present ${number}/${total}<br>${small(line)}`,
  surpriseHop: 'Boing! Super jump!',
  surpriseTurbo: (secs) => `Turbo for ${secs} seconds!`,
  surpriseMoon: (secs) => `Moon gravity for ${secs} seconds!`,
  surpriseRepair: 'Free repair: good as new!',
  huntAllFound: 'All presents found!',
  huntFinishedText: 'You found every present. Play again: they hide somewhere else every time.',
  holzToast: `Holzbrücke!<br>${small('Pedestrians only. Allegedly.')}`,
  fishes: 'Sleep with the fishes!',
  underwaterHint: 'Drive up to the bank, or press R for the road.',
  heliOn: 'Helicopter!',
  heliLanded: 'Landed',
  heliNoRoad: 'No road below to land on',
  randomSpot: 'Random spot',
  fromMap: 'From the map',
  debugOn: 'Debug on',
  debugOff: 'Debug off',
  copied: 'Copied',
  copyFailed: 'Copy failed',
  mapOsm: 'Open in OpenStreetMap (new tab)',
  mapGoogle: 'Open in Google Maps (new tab)',
  mapStreetView: 'Open in Google Street View (new tab)',
  // ---- debug panel labels and legend (#74) ----
  dbgLabCar: 'car',
  dbgLabLv95: 'Swiss',
  dbgLabWgs84: 'GPS',
  dbgLabBldg: 'nearest',
  dbgLabSize: 'car body',
  dbgLabMap: 'world',
  dbgLegendBtn: 'Explain the debug values',
  dbgLegend: '<b>car</b> x east, z south, y height, in metres (game frame) · heading in degrees, 0 = north, clockwise<br><b>Swiss</b> LV95 east / north in metres (EPSG:2056)<br><b>GPS</b> WGS84 latitude, longitude in degrees<br><b>nearest</b> bldg &lt;OSM id&gt; · &lt;h&gt; m +&lt;rh&gt; &lt;source&gt; — the building nearest the car. h = wall height up to the eaves, +rh = roof height on top (only when measured). dsm = height measured from swisstopo’s digital surface model (swissSURFACE3D) minus the terrain model, osm = OpenStreetMap height, levels or a default for the building type. 2.5 m is the lowest wall height a measured (dsm) building gets. The same text floats above each roof within 60 m.<br><b>car body</b> length × width × height of the car’s body box in metres<br><b>world</b> width × depth of the drawn map in km, and its area<br>Click the panel to copy all lines.',
  boundsOn: 'Gemeinde boundaries on',
  boundsOff: 'Gemeinde boundaries off',
  boundsNoData: 'Gemeinde boundaries: no data',
  // ---- F1 help ----
  helpTitle: 'Keys · F1 closes',
  keyAccel: 'accelerate (W or ↑ also work)',
  keySteer: 'or ← →: steer · <b>S</b> / ↓ brake, reverse',
  keyHandbrake: 'handbrake (drift)',
  keyNitro: 'Nitro (hold)',
  keyTab: 'full map (hold)',
  keySignals: 'Turn signals left · right',
  keyHorn: 'horn',
  keyCamera: 'camera: chase · near · cockpit · bumper',
  keyLookBack: 'look back (hold)',
  keyCar: 'show / hide the car',
  keyBounds: 'show / hide the Gemeinde boundaries',
  keyJump: 'jump to a landmark',
  keyHeli: 'helicopter: take off · land (Space climbs, Shift sinks)',
  keyZoom: 'zoom the map 1× · 2× · 4× · 8× (or the mouse wheel over it) · double-click or double-tap the map: put the car on the road there',
  keyTrip: 'reset the trip odometer',
  keyReset: 'back on the road',
  keyStyle: 'toggle graphic style',
  keyPhoto: 'photo: save the view as a PNG',
  keyMute: 'mute',
  keyDebug: 'debug: coordinates, building heights, map links (click the panel to copy · ?debug in the URL)',
  keyHelp: 'this help',
  keyPause: 'pause: resume · restart race · main menu',
  // ---- pause menu (#83) ----
  pauseTitle: 'Paused',
  pauseResume: 'Resume',
  pauseRestart: 'Restart race',
  pauseMenu: 'Main menu',
  pauseHint: 'Esc · P: resume',
  pauseAria: 'Pause',
  abandonTitle: 'Abandon this run?',
  abandonCancel: 'Cancel',
  abandonOk: 'Abandon',
  abandonHint: 'Esc: cancel',
  // ---- J dialog ----
  jumpTitle: 'Jump to',
  jumpSearch: 'Search landmarks',
  jumpHint: 'type to search · ↑↓ Enter · J / Esc closes',
  chipAll: 'All',
  // ---- car selection (#7) ----
  chooseCar: 'Choose car',
  carselTitle: 'Choose car',
  carselCount: (i, n) => `Car ${i} of ${n}`,
  carselPrev: 'Previous car',
  carselNext: 'Next car',
  carselRotate: 'Rotate · drag or ← →',
  statTop: 'Top speed',
  statAccel: 'Acceleration',
  statHandling: 'Handling',
  statMass: 'Mass',
  paintLabel: 'Paint',
  paintFixed: 'fixed',
  paintNavy: 'Navy',
  paintSunflower: 'Sunflower',
  paintSignal: 'Signal orange',
  paintSwiss: 'Swiss red',
  paintFlamingo: 'Flamingo',
  paintPlum: 'Plum',
  paintRhine: 'Rhine blue',
  paintIce: 'Ice',
  paintMeadow: 'Meadow',
  paintCream: 'Cream',
  paintCharcoal: 'Charcoal',
  garageLabel: (n) => `Garage · ${n} ${n === 1 ? 'vehicle' : 'vehicles'}`,
  carselBack: '‹ Back',
  carselRace: 'Race! ›',
  veh_compact_name: 'Sissle Speedster',
  veh_compact_class: 'Compact · Class B',
  veh_compact_desc: 'Small, light, a bit too eager. Fits through the old town like it was measured for it.',
  veh_delorean_name: 'Rhy Gullwing',
  veh_delorean_class: 'Stainless coupé · Class B',
  veh_delorean_desc: 'Brushed steel, gull-wing doors, 1981 on the clock. Slow off the line, but when it pulls up the whole Hochrhein turns round.',
  keyAuto: 'autopilot: drive to a place or street (O again, steering, gas or brake: you drive)',
  driveTitle: 'Drive to',
  driveHint: 'type to search · ↑↓ Enter · O / Esc closes',
  streetIn: (g) => `street · ${g}`,
  autoOn: (n) => `Autopilot → ${n}`,
  autoOff: 'Autopilot off — you drive',
  autoArrived: (n) => `Arrived: ${n}`,
  autoStuck: 'Autopilot stuck — you drive',
  autoNoRoute: 'No route from here',
  autoNoWorld: 'Autopilot needs the OSM world',
  autoLine: (n, km) => `AUTOPILOT → ${n} · ${km} km`,
  // ---- Blitz (#128) ----
  blitz: 'Blitz',
  modeBlitz: 'Blitz · Hochrhein',
  timeLeft: 'Time left',
  blitzIntro: 'The same five checkpoints and the finish — but the clock counts down. 90 seconds to start, every checkpoint adds 60. Finish with time left for a rank.',
  blitzFinishedText: 'Made it before the clock. More seconds left means a better rank — S is the one to chase.',
  blitzTimeUpText: 'The clock ran out. Checkpoints add time, so take the nearest one first.',
  cpToastBlitz: (number, name, bonus) => `Checkpoint ${number}/5 · +${bonus} s<br>${small(name)}`,
  blitzRank: 'Rank',
  blitzLeft: (time) => `${time} left · `,
  blitzBest: (time) => `Best left ${time ?? '—'}`,
  blitzTimeUp: "Time's up",
  blitzCps: (done) => `${done} / 5 checkpoints`,
};

const de = {
  sub: 'Codename Rhyflitzer · Prototyp v0.2',
  region: 'Region',
  regionMissing: (n) => `Für ${n} gibt es noch keine Daten — Du siehst den Hochrhein`,
  introEhrendingen: 'Oberdorf → Höhtal → Lägernbreite → St. Anna → Tiefenwaag. Fünf Checkpoints in beliebiger Reihenfolge, dann das Ziel Im Böndlern. Der Wanderweg ist für Wanderer. Das hat der Stoppuhr niemand gesagt.',
  finishedEhrendingen: 'Im Böndlern erreicht. Nochmals für eine bessere Linie, oder nimm nächstes Mal den Wanderweg.',
  blurbOsmEhrendingen: 'Strassen, Wanderweg, Häuser und die Surb aus OpenStreetMap, Gelände von swisstopo. Die Zeit läuft, sobald Du fährst.',
  intro: 'Sisseln → Sisslerfeld → Stein → Bad Säckingen. Fünf Checkpoints in beliebiger Reihenfolge, dann das Ziel auf dem Münsterplatz. Die Holzbrücke ist für Fussgänger. Das hat der Stoppuhr niemand gesagt.',
  finishedText: 'Münsterplatz erreicht. Nochmals für eine bessere Linie – oder nächstes Mal die andere Brücke.',
  start: 'Start',
  retry: 'Nochmals',
  styleLabel: 'Stil:',
  styleOriginal: 'Original',
  styleSmooth: 'Glatt',
  loadTerrain: 'Gelände laden (.mmh)',
  useMadeUp: 'Erfundenes Gelände verwenden',
  terrainMadeUp: 'Gelände: erfunden (sanfte Hügel, nicht gemessen)',
  terrainMeasured: (own, w, h, step, sources) => `Gelände: gemessen${own ? ' (Deine Datei)' : ''} · ${w}×${h} zu ${step} m · ${sources}`,
  terrainSaving: 'Gelände wird gespeichert, die Welt neu aufgebaut…',
  terrainCouldNotLoad: (message) => `Konnte nicht geladen werden: ${message}`,
  errNotMmh: 'Keine Map-Madness-Höhenkarte (MMH1)',
  errNoStorage: 'Dieser Browser blockiert den Speicher, das Gelände kann nicht behalten werden',
  blurbHand: 'Strassennetz von Hand aus OpenStreetMap abgezeichnet. Die Zeit läuft, sobald Du fährst.',
  blurbOsm: 'Strassen, Rhein, Häuser und Wahrzeichen aus OpenStreetMap, Gelände von swisstopo. Die Zeit läuft, sobald Du fährst.',
  worldOsm: (roads, buildings, sources) => `Welt: OpenStreetMap · ${roads} Strassen · ${buildings} Gebäude · ${sources}`,
  worldHand: 'Welt: von Hand abgezeichnet (keine data/world_hochrhein.json)',
  newRecord: 'Neuer Rekord!',
  finished: 'Im Ziel',
  notCountedJump: 'mit Sprung, zählt nicht · ',
  notCountedHeli: 'mit Helikopter, zählt nicht · ',
  notCountedAuto: 'mit Autopilot, zählt nicht · ',
  viaHolz: 'über die Holzbrücke · ',
  bestLower: 'Bestzeit',
  keyHornMute: 'Hupe (auch Enter) · Ton aus',
  keyNitroJump: 'Nitro (halten) · zu einem Wahrzeichen springen',
  keyAllKeys: 'alle Tasten',
  mode: (r) => `Zeitfahren · ${r}`,
  checkpointsLabel: 'Checkpoints',
  ready: 'Bereit',
  cpTarget: (number, name) => `Checkpoint ${number} · ${name}`,
  finishTarget: (name) => `Ziel · ${name}`,
  time: 'Zeit',
  best: (time) => `Bestzeit ${time ?? '—'}`,
  damage: 'Schaden',
  gear: 'Gang',
  trip: 'Trip',
  odo: (km) => `Total ${km} km · K setzt Trip zurück`,
  map: (r) => `Karte · ${r} ·`,
  compassAria: 'Kompass',
  compassEast: 'O',
  speedoAria: 'Tachometer',
  steerLeft: 'Links lenken',
  steerRight: 'Rechts lenken',
  accelerate: 'Gas geben',
  brake: 'Bremsen',
  handbrake: 'Handbremse',
  muted: 'Ton aus',
  soundOn: 'Ton an',
  photoSaved: 'Foto gemacht',
  photoFailed: 'Foto fehlgeschlagen',
  camera: (view) => `Kamera: ${view}`,
  camChase: 'Verfolger',
  camNear: 'Verfolger nah',
  camCockpit: 'Cockpit',
  camBumper: 'Stossstange',
  cpToast: (number, name) => `Checkpoint ${number}/5<br>${small(name)}`,
  // ---- Überraschungsjagd (#108) ----
  hunt: 'Überraschungsjagd',
  modeHunt: 'Überraschungsjagd · Hochrhein',
  presentsLabel: 'Geschenke',
  presentTarget: 'Nächstes Geschenk',
  huntStart: 'Finde die 5 Geschenke! Folge dem Pfeil.',
  presentToast: (number, total, line) => `Geschenk ${number}/${total}<br>${small(line)}`,
  surpriseHop: 'Boing! Supersprung!',
  surpriseTurbo: (secs) => `Turbo für ${secs} Sekunden!`,
  surpriseMoon: (secs) => `Mondschwerkraft für ${secs} Sekunden!`,
  surpriseRepair: 'Gratis-Reparatur: wie neu!',
  huntAllFound: 'Alle Geschenke gefunden!',
  huntFinishedText: 'Du hast alle Geschenke gefunden. Nochmals spielen: Sie verstecken sich jedes Mal woanders.',
  holzToast: `Holzbrücke!<br>${small('Nur für Fussgänger. Angeblich.')}`,
  fishes: 'Grüss mir die Fische!',
  underwaterHint: 'Fahr ans Ufer hoch, oder drück R für die Strasse.',
  heliOn: 'Helikopter!',
  heliLanded: 'Gelandet',
  heliNoRoad: 'Keine Strasse unten zum Landen',
  randomSpot: 'Zufälliger Ort',
  fromMap: 'Von der Karte',
  debugOn: 'Debug an',
  debugOff: 'Debug aus',
  copied: 'Kopiert',
  copyFailed: 'Kopieren fehlgeschlagen',
  mapOsm: 'In OpenStreetMap öffnen (neuer Tab)',
  mapGoogle: 'In Google Maps öffnen (neuer Tab)',
  mapStreetView: 'In Google Street View öffnen (neuer Tab)',
  dbgLabCar: 'Auto',
  dbgLabLv95: 'Schweiz',
  dbgLabWgs84: 'GPS',
  dbgLabBldg: 'nächstes',
  dbgLabSize: 'Karosserie',
  dbgLabMap: 'Welt',
  dbgLegendBtn: 'Debug-Werte erklären',
  dbgLegend: '<b>Auto</b> x Osten, z Süden, y Höhe, in Metern (Spielkoordinaten) · Kurs in Grad, 0 = Norden, im Uhrzeigersinn<br><b>Schweiz</b> LV95 Ost / Nord in Metern (EPSG:2056)<br><b>GPS</b> WGS84 Breite, Länge in Grad<br><b>nächstes</b> bldg &lt;OSM-ID&gt; · &lt;h&gt; m +&lt;rh&gt; &lt;Quelle&gt; — das Gebäude, das dem Auto am nächsten ist. h = Wandhöhe bis zur Traufe, +rh = Dachhöhe darüber (nur wenn gemessen). dsm = digitales Oberflächenmodell (DSM): Höhe gemessen aus dem Oberflächenmodell von swisstopo (swissSURFACE3D) minus Geländemodell, osm = Höhe, Geschosse oder Standardwert je Gebäudetyp aus OpenStreetMap. 2.5 m ist die kleinste Wandhöhe eines gemessenen (dsm) Gebäudes. Derselbe Text schwebt im Umkreis von 60 m über jedem Dach.<br><b>Karosserie</b> Länge × Breite × Höhe der Karosserie in Metern<br><b>Welt</b> Breite × Tiefe der gezeichneten Karte in km, und ihre Fläche<br>Ein Klick aufs Panel kopiert alle Zeilen.',
  boundsOn: 'Gemeindegrenzen an',
  boundsOff: 'Gemeindegrenzen aus',
  boundsNoData: 'Gemeindegrenzen: keine Daten',
  helpTitle: 'Tasten · F1 schliesst',
  keyAccel: 'Gas geben (W oder ↑ gehen auch)',
  keySteer: 'oder ← →: lenken · <b>S</b> / ↓ bremsen, rückwärts',
  keyHandbrake: 'Handbremse (Drift)',
  keyNitro: 'Nitro (halten)',
  keyTab: 'ganze Karte (halten)',
  keySignals: 'Blinker links · rechts',
  keyHorn: 'Hupe',
  keyCamera: 'Kamera: Verfolger · nah · Cockpit · Stossstange',
  keyLookBack: 'zurückschauen (halten)',
  keyCar: 'Auto zeigen / verstecken',
  keyBounds: 'Gemeindegrenzen ein- / ausblenden',
  keyJump: 'zu einem Wahrzeichen springen',
  keyHeli: 'Helikopter: abheben · landen (Leertaste steigt, Shift sinkt)',
  keyZoom: 'Karte zoomen 1× · 2× · 4× · 8× (oder Mausrad darüber) · Doppelklick oder Doppeltipp auf die Karte: Auto dort auf die Strasse setzen',
  keyTrip: 'Tageskilometer zurücksetzen',
  keyReset: 'zurück auf die Strasse',
  keyStyle: 'Grafikstil wechseln',
  keyPhoto: 'Foto: Ansicht als PNG speichern',
  keyMute: 'Ton aus',
  keyDebug: 'Debug: Koordinaten, Gebäudehöhen, Kartenlinks (Panel anklicken zum Kopieren · ?debug in der URL)',
  keyHelp: 'diese Hilfe',
  keyPause: 'Pause: weiter · Rennen neu starten · Hauptmenü',
  pauseTitle: 'Pause',
  pauseResume: 'Weiter',
  pauseRestart: 'Rennen neu starten',
  pauseMenu: 'Hauptmenü',
  pauseHint: 'Esc · P: weiter',
  pauseAria: 'Pause',
  abandonTitle: 'Diesen Lauf abbrechen?',
  abandonCancel: 'Abbrechen',
  abandonOk: 'Verwerfen',
  abandonHint: 'Esc: abbrechen',
  jumpTitle: 'Springen nach',
  jumpSearch: 'Wahrzeichen suchen',
  jumpHint: 'tippen zum Suchen · ↑↓ Enter · J / Esc schliesst',
  chipAll: 'Alle',
  // ---- car selection (#7) ----
  chooseCar: 'Auto wählen',
  carselTitle: 'Auto wählen',
  carselCount: (i, n) => `Auto ${i} von ${n}`,
  carselPrev: 'Vorheriges Fahrzeug',
  carselNext: 'Nächstes Fahrzeug',
  carselRotate: 'Drehen · ziehen oder ← →',
  statTop: 'Höchsttempo',
  statAccel: 'Beschleunigung',
  statHandling: 'Handling',
  statMass: 'Masse',
  paintLabel: 'Lack',
  paintFixed: 'fest',
  paintNavy: 'Marine',
  paintSunflower: 'Sonnenblume',
  paintSignal: 'Signalorange',
  paintSwiss: 'Schweizer Rot',
  paintFlamingo: 'Flamingo',
  paintPlum: 'Pflaume',
  paintRhine: 'Rheinblau',
  paintIce: 'Eis',
  paintMeadow: 'Wiese',
  paintCream: 'Creme',
  paintCharcoal: 'Anthrazit',
  garageLabel: (n) => `Garage · ${n} ${n === 1 ? 'Fahrzeug' : 'Fahrzeuge'}`,
  carselBack: '‹ Zurück',
  carselRace: 'Los! ›',
  veh_compact_name: 'Sissle Speedster',
  veh_compact_class: 'Kompakt · Klasse B',
  veh_compact_desc: 'Klein, leicht, etwas übereifrig. Passt durch die Altstadt, als wäre sie dafür vermessen worden.',
  veh_delorean_name: 'Rhy Gullwing',
  veh_delorean_class: 'Edelstahl-Coupé · Klasse B',
  veh_delorean_desc: 'Gebürsteter Stahl, Flügeltüren, Baujahr 1981. Träge beim Anfahren, aber wenn er vorfährt, dreht sich der ganze Hochrhein um.',
  keyAuto: 'Autopilot: zu einem Ort oder einer Strasse fahren (nochmals O, lenken, Gas oder Bremse: selbst fahren)',
  driveTitle: 'Fahren nach',
  driveHint: 'tippen zum Suchen · ↑↓ Enter · O / Esc schliesst',
  streetIn: (g) => `Strasse · ${g}`,
  autoOn: (n) => `Autopilot → ${n}`,
  autoOff: 'Autopilot aus — selbst fahren',
  autoArrived: (n) => `Angekommen: ${n}`,
  autoStuck: 'Autopilot steckt fest — selbst fahren',
  autoNoRoute: 'Keine Route von hier',
  autoNoWorld: 'Autopilot braucht die OSM-Welt',
  autoLine: (n, km) => `AUTOPILOT → ${n} · ${km} km`,
  // ---- Blitz (#128) ----
  blitz: 'Blitz',
  modeBlitz: 'Blitz · Hochrhein',
  timeLeft: 'Restzeit',
  blitzIntro: 'Dieselben fünf Checkpoints und das Ziel — aber die Uhr läuft rückwärts. 90 Sekunden zum Start, jeder Checkpoint gibt 60 dazu. Mit Restzeit ins Ziel gibt einen Rang.',
  blitzFinishedText: 'Vor der Uhr im Ziel. Je mehr Restzeit, desto besser der Rang — S ist das Ziel.',
  blitzTimeUpText: 'Die Zeit ist abgelaufen. Checkpoints geben Zeit — nimm zuerst den nächsten.',
  cpToastBlitz: (number, name, bonus) => `Checkpoint ${number}/5 · +${bonus} s<br>${small(name)}`,
  blitzRank: 'Rang',
  blitzLeft: (time) => `${time} Restzeit · `,
  blitzBest: (time) => `Beste Restzeit ${time ?? '—'}`,
  blitzTimeUp: 'Zeit ist um',
  blitzCps: (done) => `${done} / 5 Checkpoints`,
};

export const STRINGS = { en, de };

export function translate(lang, key, ...args) {
  const table = STRINGS[lang] || en;
  const value = key in table ? table[key] : key in en ? en[key] : key;
  return typeof value === 'function' ? value(...args) : value;
}
